### PR TITLE
Fix near location search

### LINKED ISSUE #342: Near location search not working
As reported in https://github.com/code4recovery/12-step-meeting-list/discussions/1255

It just submits and then empties the field and returns to regular search mode

### PR DESCRIPTION
**Pull request by joshreisner**
this is weird, i'm not sure how long "near location" search has not been working 

seems the problem is `onSubmit` is not firing, the simplest solution i found was to add a hidden submit button

alternately we could listen for the enter key in the input onChange and fire locationSearch if `mode === "location"`

could not tell from the history when this stopped working

closes #342

### CODE REVIEW

**Comment by joshreisner** [comment]
to see the problem, go to [this link](https://tsml-ui.code4recovery.org/tests/aasanjose.html?mode=location) and search for `sap center`

to see the fix, go to [this link](https://deploy-preview-344--tsml-ui.netlify.app/tests/aasanjose.html?mode=location) and search `sap center`

File: src/components/Controls.tsx [hunk 1]
```diff
@@ -164,6 +164,7 @@ export default function Controls({ state, setState, mapbox }: ControlsProps) {
               state.input.mode === 'location' ? search : state.input.search
             }
           />
+          <input type="submit" hidden />
```
Comment (michael-duren) [inline src/components/Controls.tsx:167]: Makes sense to add this.
Also not sure how this was working before the enter key press behavior seems sort of unpredictable currently.

Comment (michael-duren) [reply src/components/Controls.tsx:167]: I think maybe because there are buttons in the <form> field the browser might be interpreting one of those as a submit?

**Review by michael-duren — APPROVED** [review]
